'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebEditarCliente

    '''<summary>
    '''lblTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''inputNombreComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputNombreComercial As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rfvNombreComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNombreComercial As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''inputRazonSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputRazonSocial As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rfvRazonSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRazonSocial As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''inputDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputDocumento As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''revDUI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revDUI As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDocumento As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''inputTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputTelefono As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''revTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revTelefono As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTelefono As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''inputCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputCorreo As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''revCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revCorreo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCorreo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartamento As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMunicipio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''inputDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputDireccion As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''rfvDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDireccion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''inputActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputActivo As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
End Class
